export const gosList = [
  "Amphisbaena",
  "Barnacle Bess",
  "Bullywug Croaker",
  "Bullywug Royal",
  "Captain Xendros",
  "Drowned Ascetic",
  "Drowned Assassin",
  "Drowned Blade",
  "Drowned Master",
  "Fish",
  "Giant Coral Snake",
  "Giant Sea Eel",
  "Giant White Moray Eel",
  "Harpy Matriarch",
  "Juvenile Kraken",
  "Koalinth",
  "Koalinth Sergeant",
  "Krell Grohlg",
  "Kysh",
  "Living Iron Statue",
  "Lizardfolk Commoner",
  "Lizardfolk Render",
  "Lizardfolk Scaleshield",
  "Lizardfolk Subchief",
  "Locathah",
  "Locathah Hunter",
  "Master Refrum",
  "Maw of Sekolah",
  "Merfolk Salvager",
  "Merfolk Scout",
  "Minotaur Living Crystal Statue",
  "Monstrous Peryton",
  "Mr. Dory",
  "Oceanus",
  "Othokent",
  "Pirate Bosun",
  "Pirate Captain",
  "Pirate Deck Wizard",
  "Pirate First Mate",
  "Rip Tide Priest",
  "Sahuagin Blademaster",
  "Sahuagin Champion",
  "Sahuagin Coral Smasher",
  "Sahuagin Deep Diver",
  "Sahuagin Hatchling Swarm",
  "Sahuagin High Priestess",
  "Sahuagin Wave Shaper",
  "Sanbalet",
  "Sauriv",
  "Shell Shark",
  "Skeletal Alchemist",
  "Skeletal Juggernaut",
  "Skeletal Swarm",
  "Skum",
  "Thousand Teeth",
  "Vampiric Jade Statue",
  "Yalaga Maladwyn",
];
