// export const filters = [
//   { category: "Cmc", data: ["Equal to", "Greater then", "Lesser then"] },
//   {
//     category: "Color",
//     data: [
//       "W",
//       "U",
//       "B",
//       "R",
//       "G",
//       //   "WU",
//       //   "WB",
//       //   "RW",
//       //   "GW",
//       //   "UB",
//       //   "UR",
//       //   "UG",
//       //   "BR",
//       //   "BG",
//       //   "RG",
//       //   "WUB",
//       //   "WUR",
//       //   "WUG",
//       //   "WBR",
//       //   "WBG",
//       //   "WRG",
//       //   "UBR",
//       //   "UBG",
//       //   "BRG",
//       //   "WUBR",
//       //   "WUBG",
//       //   "WBRG",
//       //   "UBRG",
//       //   "WUBRG",
//     ],
//   },
//   {
//     category: "Rarity",
//     data: ["common", "uncommon", "rare", "mythical rare"],
//   },
//   {
//     category: "Type",
//     data: [
//       "creature",
//       "enchantment",
//       "land",
//       "artifact",
//       "planeswalker",
//       "instant",
//       "sorcery",
//     ],
//   },
// ];

export const filters = [
  {
    category: "combinations",
    data: [
      "White Artifact",
      "Blue Artifact",
      "Black Artifact",
      "Red Artifact",
      "Green Artifact",
      "Colorless Artifact",
      "White Creature",
      "Blue Creature",
      "Black Creature",
      "Red Creature",
      "Green Creature",
      "Colorless Creature",
      "White Enchantment",
      "Blue Enchantment",
      "Black Enchantment",
      "Red Enchantment",
      "Green Enchantment",
      "Colorless Enchantment",
      "White Instant",
      "Blue Instant",
      "Black Instant",
      "Red Instant",
      "Green Instant",
      "Colorless Instant",
      "White Planeswalker",
      "Blue Planeswalker",
      "Black Planeswalker",
      "Red Planeswalker",
      "Green Planeswalker",
      "Colorless Planeswalker",
      "White Sorcery",
      "Blue Sorcery",
      "Black Sorcery",
      "Red Sorcery",
      "Green Sorcery",
      "Colorless Sorcery",
    ],
  },
  {
    category: "cmc",
    data: [
      "< 2",
      "< 3",
      "< 4",
      "< 5",
      "< 6",
      "> 1",
      "> 2",
      "> 3",
      "> 4",
      "> 5",
      "> 6",
      "= 1",
      "= 2",
      "= 3",
      "= 4",
      "= 5",
      "= 6",
    ],
  },
];
